<?php

namespace BlogBundle\Entity;

/**
 * BlogPostTagsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogPostTagsRepository extends \Doctrine\ORM\EntityRepository
{
}
