<?php

namespace BlogBundle\Entity;

use BlogBundle\Extension\Entity\SecureRepository;

/**
 * BlogPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogPostRepository extends \Doctrine\ORM\EntityRepository
{
    use SecureRepository;
    protected static $secure_code = "blog_post";
}
