<?php

namespace BlogBundle\Entity;

use BlogBundle\Extension\Entity\SecureRepository;

/**
 * TagsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagsRepository extends \Doctrine\ORM\EntityRepository {

    use SecureRepository;

    protected static $secure_code = "blog_tag";

}
