auth:
    resource: "@AuthBundle/Controller/"
    type:     annotation
    prefix:   /

news:
    resource: "@NewsBundle/Controller/"
    type:     annotation
    prefix:   /

  
kms_froala_editor:
  resource: "@KMSFroalaEditorBundle/Resources/config/routing.yml"
  prefix:   /froalaeditor    



