#auth:
 #   resource: "@AuthBundle/Controller/"
#    type:     annotation
#    prefix:   /

blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"    
    
kms_froala_editor:
  resource: "@KMSFroalaEditorBundle/Resources/config/routing.yml"
  prefix:   /froalaeditor    



