security:
    encoders:
        AuthBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        our_users:
            entity: { class: AuthBundle\Entity\User, property: email }
       # in_memory:
        #    memory:
         #       users:
          #          admin:
           #             password: root
            #            roles: 'ROLE_USER'    

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            logout_on_user_change: true
            anonymous: ~
       #     provider: in_memory
            guard:
                authenticators:
                    - auth.security.login_form_authenticator
            logout:
                path: /logout
                target: /
            form_login:
                login_path: /login
                check_path: /login 
            remember_me:
                secret:   '%secret%'
                lifetime: 300
                path:     /
                remember_me_parameter: _remember_me
        

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        


        