<?php

namespace NewsBundle\Entity;

use NewsBundle\Extension\Entity\SecureRepository;

/**
 * TagsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilesRepository extends \Doctrine\ORM\EntityRepository {

    use SecureRepository;

    protected static $secure_code = "news_file"
            . "";

}
