<?php

namespace NewsBundle\Entity;

use NewsBundle\Extension\Entity\SecureRepository;

/**
 * NewsPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsPostRepository extends \Doctrine\ORM\EntityRepository
{
    use SecureRepository;
    protected static $secure_code = "news_post";
}
